### ISSUE TITLE
ECG CoCa model training tokenizer mismatch issue 

### ISSUE THREAD

**Issue by gustmd0121** [YubaoZhao/ECG-Chat#1]
Hello and thank you for publishing the source code, I am very interested in your work! 
While attempting to train your ECG CoCa model following the instructions given in the readme, I am facing issues in the encoding text part of the coca model, specifically
```
    def _encode_text(self, text, normalize: bool = True):
        text_latent, token_emb = self.text(text)
        text_latent = F.normalize(text_latent, dim=-1) if normalize else text_latent
        return text_latent, token_emb 
```
where I get the error as below
```
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [130,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```
I think it is because of the mismatch between the BertModel tokenizer and the tokenizer used for the ECG text. Could you look into this issue? Thank you.

**Comment by YubaoZhao** [comment]
Hello, thanks for your interest. Could you please show me your config file?

**Comment by gustmd0121** [comment]
Hello you can disregard this issue. I ran into the issue while debugging and works fine when using your shell script. Thank you!

**Comment by gustmd0121** [comment]
Actually nevermind. I ran into the same issue when running with coca_train_scripts.sh. The config I used is 
`torchrun --nproc_per_node 1 -m training.main --save-frequency 1 --val-frequency 5 --report-to wandb --mimic-iv-ecg-path="/nfs/mimic-iv-ecg/" --warmup 10000  --batch-size 16 --lr 1e-4 --wd 0.1 --epochs 20 --workers 2 --model coca_ViT-B-32 --ptbxl-path='nfs/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3/" --lock-text --grad-clip-norm 0.5
` 

But I get the error as below
`../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [11,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/training/main.py", line 541, in <module>
    main(sys.argv[1:])
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/training/main.py", line 430, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, args, tb_writer=writer)
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/training/train.py", line 99, in train_one_epoch
    model_out = model(ecgs, texts)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/open_clip/coca_model.py", line 178, in forward
    text_latent, token_embs = self._encode_text(text)
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/open_clip/coca_model.py", line 145, in _encode_text
    text_latent, token_emb = self.text(text)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs_edlab/hschung/ECG-Chat/open_clip/open_clip/hf_model.py", line 156, in forward
    out = self.transformer(input_ids=x, attention_mask=attn_mask)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1073, in forward
    embedding_output = self.embeddings(
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 211, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/home/hschung/anaconda3/envs/fairseq/lib/python3.10/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

I think there is still error in the token embedding part of the code.

**Comment by YubaoZhao** [comment]
Hi, do you still have this error? I run the code successfully on my 4090. Which GPU you are using?

**Comment by PeterZ163426** [comment]
I also encountered the same problem. I tried 4090 and V100, and the above error occurred.

**Comment by PeterZ163426** [comment]
I found that this problem is caused by position_ids and token_type_ids inside the Bert model, in lines 195-200 of modeling_bert.py,
 ```
self.register_buffer(
    "position_ids", torch.arange(config.max_position_embeddings).expand((1, -1)), persistent=False
)
self.register_buffer(
    "token_type_ids", torch.zeros(self.position_ids.size(), dtype=torch.long), persistent=False
)
```
If position_ids and token_type_ids are not displayed, the self.position_ids and self.token_type_ids registered in the buffer will be used. I printed them out and found that they were a series of large numbers, not 0-max_position_embeddings. Therefore, I added position_ids and token_type_ids to line 155 of hf_model.py.
```
def forward(self, x: TensorType):
        attn_mask = (x != self.config.pad_token_id).long()
        token_type_ids = torch.zeros_like(x)
        position_ids = torch.arange(x.size(1), device=x.device).unsqueeze(0)
        # out = self.transformer(input_ids=x, attention_mask=attn_mask)
        out = self.transformer(input_ids=x, attention_mask=attn_mask, token_type_ids=token_type_ids, position_ids=position_ids)
        pooled_out = self.pooler(out, attn_mask)
```
The problem is solved.
But I still don't know why this problem occurs. 😥

**Comment by YubaoZhao** [comment]
Thank you @PeterZ163426 for your effort! This error is caused by the code in line 266 of open_clip/open_clip/factory.py
```python
model.to_empty(device=device)
```
This line is essential for initializing the ECG-LLaVA, but will cause this error when initializing the CoCa. I moved this line of code to the `get_ecg_encoder`  function in main.py, this error seems to have been fixed.
